export const INCREMENT_PAGENUM = 'INCREMENT_PAGENUM';
export const DECREMENT_PAGENUM = 'DECREMENT_PAGENUM';

export const ADD_MOVIES_TO_STATE = 'ADD_MOVIES_TO_STATE';
export const CLEAN_STATE_FROM_MOVIES ='CLEAN_STATE_FROM_MOVIES';