export const INCREMENT_PAGENUM = 'INCREMENT_PAGENUM';
export const DECREMENT_PAGENUM = 'DECREMENT_PAGENUM';

export const ADD_MOVIES_TO_STATE = 'ADD_MOVIES_TO_STATE';
export const PAGE_COUNT ='PAGE_COUNT';

export const SEARCH_STRING = 'SEARCH_STRING';
export const CLEAN_STATE = 'CLEAN_STATE';

